# Generated by Django 4.2.1 on 2023-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_uz', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('file', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_uz', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('News', 'News'), ('Articles', 'Articles'), ('Scientific_Articles', 'Scientific Articles'), ('Books', 'Books'), ('Scientific_Research', 'Scientific Research'), ('Magazines', 'Magazines')], max_length=50)),
                ('category_uz', models.CharField(choices=[('News', 'News'), ('Articles', 'Articles'), ('Scientific_Articles', 'Scientific Articles'), ('Books', 'Books'), ('Scientific_Research', 'Scientific Research'), ('Magazines', 'Magazines')], max_length=50, null=True)),
                ('category_en', models.CharField(choices=[('News', 'News'), ('Articles', 'Articles'), ('Scientific_Articles', 'Scientific Articles'), ('Books', 'Books'), ('Scientific_Research', 'Scientific Research'), ('Magazines', 'Magazines')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Description')),
                ('text_uz', models.TextField(null=True, verbose_name='Description')),
                ('text_en', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='video/')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
