# Generated by Django 4.2.1 on 2023-05-18 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOftheCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('ARTICLES', 'Articles'), ('COUNTRYIMAGE', 'Image of the Country'), ('SCIENTIFIC_ARTICLES', 'Scientific Articles'), ('BOOKS', 'Books'), ('INTERNATIONAL_PROJECTS', 'International Projects')], max_length=50)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('ARTICLES', 'Articles'), ('COUNTRYIMAGE', 'Image of the Country'), ('SCIENTIFIC_ARTICLES', 'Scientific Articles'), ('BOOKS', 'Books'), ('INTERNATIONAL_PROJECTS', 'International Projects')], max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='video/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
