# Generated by Django 4.2.1 on 2023-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_uz', models.CharField(max_length=500, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('ARTICLES', 'Articles'), ('COUNTRYIMAGE', 'Image of the Country'), ('SCIENTIFIC_ARTICLES', 'Scientific Articles'), ('BOOKS', 'Books'), ('INTERNATIONAL_PROJECTS', 'International Projects'), ('ANNOUNCEMENT', 'Announcement'), ('PHD_AFTOREFERAT', 'Phd Aftoreferati'), ('SCIENTIFIC_RESEARCH', 'Scientific Research'), ('MAGAZINES', 'Magazines'), ('FOREIGN_JOURNALS', 'Foreign Journals'), ('COLLECTIONS', 'Collections'), ('TRAINING', 'Training'), ('WORKSHOPS', 'Workshops'), ('SPEECHES', 'Speeches'), ('PRESENTATIONS', 'Presentations')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='suggestions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
