# Generated by Django 4.2.1 on 2023-05-18 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_imageofthecountry_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 12, 24, 896653)),
        ),
    ]
