# Generated by Django 4.2.1 on 2023-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_text_en_product_text_uz_product_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category_en',
            field=models.CharField(choices=[('NEWS', 'News'), ('ARTICLES', 'Articles'), ('COUNTRYIMAGE', 'Image of the Country'), ('SCIENTIFIC_ARTICLES', 'Scientific Articles'), ('BOOKS', 'Books'), ('INTERNATIONAL_PROJECTS', 'International Projects'), ('ANNOUNCEMENT', 'Announcement'), ('PHD_AFTOREFERAT', 'Phd Aftoreferati'), ('SCIENTIFIC_RESEARCH', 'Scientific Research'), ('MAGAZINES', 'Magazines'), ('FOREIGN_JOURNALS', 'Foreign Journals'), ('COLLECTIONS', 'Collections'), ('TRAINING', 'Training'), ('WORKSHOPS', 'Workshops'), ('SPEECHES', 'Speeches'), ('PRESENTATIONS', 'Presentations')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='category_uz',
            field=models.CharField(choices=[('NEWS', 'News'), ('ARTICLES', 'Articles'), ('COUNTRYIMAGE', 'Image of the Country'), ('SCIENTIFIC_ARTICLES', 'Scientific Articles'), ('BOOKS', 'Books'), ('INTERNATIONAL_PROJECTS', 'International Projects'), ('ANNOUNCEMENT', 'Announcement'), ('PHD_AFTOREFERAT', 'Phd Aftoreferati'), ('SCIENTIFIC_RESEARCH', 'Scientific Research'), ('MAGAZINES', 'Magazines'), ('FOREIGN_JOURNALS', 'Foreign Journals'), ('COLLECTIONS', 'Collections'), ('TRAINING', 'Training'), ('WORKSHOPS', 'Workshops'), ('SPEECHES', 'Speeches'), ('PRESENTATIONS', 'Presentations')], max_length=50, null=True),
        ),
    ]
