# Generated by Django 4.2.1 on 2023-05-18 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageofthecountry',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_created',
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
