# Generated by Django 4.1 on 2023-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_posts_category_alter_posts_category_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booksmodel",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="booksmodel",
            name="text_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="booksmodel",
            name="title_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="booksmodel",
            name="title_uz",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
