# Generated by Django 4.2.1 on 2023-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ARTICLES', 'Articles'), ('COUNTRYIMAGE', 'Image of the Country'), ('SCIENTIFIC_ARTICLES', 'Scientific Articles'), ('BOOKS', 'Books'), ('INTERNATIONAL_PROJECTS', 'International Projects'), ('ANNOUNCEMENT', 'Announcement'), ('PHD_AFTOREFERAT', 'Phd Aftoreferati'), ('SCIENTIFIC_RESEARCH', 'Scientific Research'), ('MAGAZINES', 'Magazines'), ('FOREIGN_JOURNALS', 'Foreign Journals')], max_length=50),
        ),
    ]
