# Generated by Django 4.1 on 2023-05-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_booksmodel_text_en_booksmodel_text_uz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booksmodel",
            name="text_en",
        ),
        migrations.RemoveField(
            model_name="booksmodel",
            name="text_uz",
        ),
        migrations.RemoveField(
            model_name="booksmodel",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="booksmodel",
            name="title_uz",
        ),
    ]
