# Generated by Django 4.1 on 2023-05-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_booksmodel_text_en_booksmodel_text_uz_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BooksModel",
        ),
    ]
