# Generated by Django 4.2.1 on 2023-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mymodel_my_choice_alter_mymodel_my_choice_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_choice',
            field=models.CharField(choices=[('News', 'News'), ('Yangiliklar', 'Yangiliklar'), ('Articles', 'Articles'), ('Maqolalar', 'Maqolalar'), ('CHOICE_3', 'Choice 3'), ('Books', 'Books'), ('Kitoblar', 'Kitoblar')], max_length=500),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='my_choice_en',
            field=models.CharField(choices=[('News', 'News'), ('Yangiliklar', 'Yangiliklar'), ('Articles', 'Articles'), ('Maqolalar', 'Maqolalar'), ('CHOICE_3', 'Choice 3'), ('Books', 'Books'), ('Kitoblar', 'Kitoblar')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='my_choice_uz',
            field=models.CharField(choices=[('News', 'News'), ('Yangiliklar', 'Yangiliklar'), ('Articles', 'Articles'), ('Maqolalar', 'Maqolalar'), ('CHOICE_3', 'Choice 3'), ('Books', 'Books'), ('Kitoblar', 'Kitoblar')], max_length=500, null=True),
        ),
    ]
